### PR TITLE
Migrated Typesafe Config facade into separate dependency project (Res…

### PR DESCRIPTION
**Pull request by darkfrog26**
Resolves https://github.com/akka-js/shocon/issues/22

### CODE REVIEW

**Comment by andreaTP** [comment]
that was fast! give me a little to check everything ;-)

**Comment by darkfrog26** [comment]
No problem.  I didn't really change any code, just moved things around and added another cross project to SBT.

**Comment by darkfrog26** [comment]
BTW, it doesn't look like your tests are running.  I'm not sure if that's my fault or not...

**Comment by darkfrog26** [comment]
@andreaTP any updates on this?  It's blocking a new release of my Profig project.

**Comment by andreaTP** [comment]
ok, let me have a look

**Comment by andreaTP** [comment]
@darkfrog26 do you mind to enable travis?

**Comment by darkfrog26** [comment]
@andreaTP I don't understand...it's showing that Travis built successfully for this PR

**Comment by andreaTP** [comment]
the approach looks good but I will keep the name `shocon` for the facade.
do you mind to rename `shocon` -> `shocon-parser` and `facade` -> back to `shocon` ?

**Comment by andreaTP** [comment]
you are right on travis, my bad.

**Comment by darkfrog26** [comment]
Done

**Comment by darkfrog26** [comment]
I didn't change the variable name in the build, but the artifacts are modified.

**Comment by darkfrog26** [comment]
if you want the variables renamed just let me know.

**Comment by andreaTP** [comment]
LGTM

**Comment by andreaTP** [comment]
I'll try to release soon.

**Comment by darkfrog26** [comment]
Thanks, I appreciate it.

**Pull request merged**
